# Generated by Django 4.0 on 2021-12-13 22:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsOutlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('link_to', models.URLField()),
                ('rss_source', models.URLField()),
                ('year_score', models.IntegerField(default=0)),
                ('month_score', models.IntegerField(default=0)),
                ('week_score', models.IntegerField(default=0)),
                ('day_score', models.IntegerField(default=0)),
                ('year_volume', models.IntegerField(default=0)),
                ('month_volume', models.IntegerField(default=0)),
                ('week_volume', models.IntegerField(default=0)),
                ('day_volume', models.IntegerField(default=0)),
                ('year_positive_points', models.IntegerField(default=0)),
                ('month_positive_points', models.IntegerField(default=0)),
                ('week_positive_points', models.IntegerField(default=0)),
                ('day_positive_points', models.IntegerField(default=0)),
                ('year_negative_points', models.IntegerField(default=0)),
                ('month_negative_points', models.IntegerField(default=0)),
                ('week_negative_points', models.IntegerField(default=0)),
                ('day_negative_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SingleDailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.date.today)),
                ('total_negative_points', models.IntegerField(default=0)),
                ('total_positive_points', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('volume', models.IntegerField(default=0)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainfunc.newsoutlet')),
            ],
        ),
    ]
