# Generated by Django 4.0 on 2021-12-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainfunc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsoutlet',
            name='rss_source',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
