# Generated by Django 4.0 on 2021-12-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainfunc', '0002_alter_newsoutlet_rss_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsoutlet',
            name='tag',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
