# Generated by Django 4.0 on 2022-01-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainfunc', '0004_newsoutlet_advertiser_newsoutlet_theme1'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsoutlet',
            name='theme2',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='newsoutlet',
            name='theme3',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
